services:
  services-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: services-service
    ports:
      - "9003:9003"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
